export const manualSections = [
  {
    title: "Mapa general del sistema",
    accent: "#0f766e",
    routeLabel: "Rutas base: /home, /hoja_servicio, /servicios, /clientes, /POS, /productos, /reportes y /configuracion",
    tags: ["Operacion diaria", "Vista global"],
    summary:
      "El sistema centraliza recepcion de servicios, seguimiento tecnico, clientes, ventas, inventario, reportes y configuracion. Tambien incluye consulta publica de estatus por folio o QR.",
    actions: [
      "Operar todo el ciclo desde una sola plataforma: registrar, dar seguimiento, cobrar e imprimir.",
      "Separar modulos internos del taller o negocio y modulos publicos orientados al cliente.",
      "Trabajar con permisos por usuario para mostrar solo las secciones necesarias.",
      "Mantener una sola fuente de informacion entre servicio, ticket, POS y reportes.",
    ],
    workflow: [
      "Inicia sesion con un usuario autorizado y entra al panel principal.",
      "Elige el modulo segun la tarea del momento: servicio, cliente, POS o configuracion.",
      "Registra cambios durante el dia y usa reportes para validar resultados y cierre.",
      "Comparte QR o folio al cliente para que consulte su avance sin llamar al taller.",
    ],
    notes: [
      "La barra superior muestra solo los accesos permitidos para el usuario actual.",
      "Configuracion concentra empresa, empleados, servicios, POS, apariencia e impresoras.",
      "La consulta publica funciona sin iniciar sesion.",
      "Los reportes integran ventas, servicios realizados, tickets y cortes de caja.",
    ],
    figure: "systemMap",
  },
  {
    title: "Acceso y navegacion",
    accent: "#2563eb",
    routeLabel: "Acceso: /login | Navegacion: barra superior y menu de usuario",
    tags: ["Primer ingreso", "Permisos"],
    summary:
      "La pantalla de acceso valida correo, contrasena, autorizacion y estado del usuario. Al entrar, el sistema registra presencia y arma la navegacion segun el rol y permisos disponibles.",
    actions: [
      "Entrar con correo y contrasena asignados por administracion.",
      "Mostrar nombre real del empleado en la barra superior cuando existe en base de datos.",
      "Abrir notificaciones, revisar nombre del usuario activo y cerrar sesion con seguridad.",
      "Usar la version movil del menu cuando se trabaja desde pantallas pequenas.",
    ],
    workflow: [
      "Abre la ruta /login y captura las credenciales del usuario.",
      "Si el usuario es valido y esta activo, el sistema redirige a /home.",
      "La barra superior muestra accesos a Servicios, Clientes, POS y Configuracion segun permisos.",
      "Cuando termines, cierra sesion desde el menu del usuario.",
    ],
    notes: [
      "Si el usuario no esta en autorizados o aparece inactivo, el acceso se bloquea.",
      "El nombre mostrado prioriza el registro de empleado antes que el correo.",
      "La campana centraliza avisos operativos y recordatorios importantes.",
      "La experiencia cambia segun permisos como servicios.crear, servicios.ver o ventas.pos.",
    ],
    figure: "loginNav",
  },
  {
    title: "Inicio y panel principal",
    accent: "#16a34a",
    routeLabel: "Pantalla principal: /home",
    tags: ["KPIs", "Acciones rapidas"],
    summary:
      "Inicio resume la operacion del negocio con tarjetas, alertas, accesos rapidos y listas de servicios. El contenido se adapta al rol del usuario para priorizar lo que necesita ver primero.",
    actions: [
      "Revisar KPIs de ventas, clientes, servicios y caja del dia.",
      "Abrir rapidamente un nuevo servicio, el listado de servicios, clientes, POS o inventario.",
      "Consultar servicios listos para entrega, servicios sin fecha y servicios por cobrar.",
      "Descargar el PDF del corte del dia cuando ya exista cierre disponible.",
    ],
    workflow: [
      "Al entrar revisa notificaciones y el resumen de caja para detectar pendientes.",
      "Usa las tarjetas rapidas para saltar directo al modulo que necesitas.",
      "Abre los servicios listos o por cobrar desde las listas del tablero.",
      "Cierra el dia volviendo al panel para validar que la caja y la operacion esten completas.",
    ],
    notes: [
      "El panel puede mostrar metricas distintas para administracion, tecnico o vendedor.",
      "Las listas del tablero abren el detalle del servicio con un clic.",
      "Los servicios por cobrar enlazan directamente con POS.",
      "Las alertas ayudan a seguir fechas prometidas y pendientes del taller.",
    ],
    figure: "dashboard",
  },
  {
    title: "Generar hoja de servicio",
    accent: "#7c3aed",
    routeLabel: "Recepcion de servicios: /hoja_servicio",
    tags: ["Recepcion", "PDF y autoimpresion"],
    summary:
      "La hoja de servicio permite registrar entradas nuevas con cliente, equipo, diagnostico y campos dinamicos por tipo de negocio. Desde aqui se activa la generacion de PDF y la impresion automatica segun configuracion.",
    actions: [
      "Buscar clientes similares mientras se escribe el nombre y reutilizar sus datos.",
      "Cambiar el tipo de negocio o dispositivo para mostrar campos personalizados.",
      "Capturar diagnostico, precio, observaciones y datos especiales del equipo o vehiculo.",
      "Guardar el servicio y disparar ticket, hoja de servicio o ambos segun las impresoras configuradas.",
    ],
    workflow: [
      "Selecciona o escribe el cliente y confirma telefono y direccion.",
      "Elige tipo de dispositivo y completa marca, modelo, serie o anio segun aplique.",
      "Captura el trabajo solicitado y los campos personalizados visibles.",
      "Guarda el registro para generar folio, PDF y autoimpresion si estan habilitados.",
    ],
    notes: [
      "La interfaz incluye navegacion por flechas para elegir sugerencias de clientes.",
      "Puedes omitir el numero de serie cuando el negocio no lo requiera.",
      "En computo se apoya en un catalogo de marcas y modelos para autocompletar datos.",
      "La hoja de servicio respeta tamano Carta o A4 y puede imprimirse en modo silencioso.",
    ],
    figure: "serviceForm",
  },
  {
    title: "Servicios y seguimiento",
    accent: "#d97706",
    routeLabel: "Listado operativo: /servicios",
    tags: ["Pendientes", "Historial"],
    summary:
      "El modulo de Servicios muestra todos los folios en dos vistas: pendientes e historial. Desde aqui se abre el detalle del servicio para continuar el proceso tecnico o revisar trabajos ya cerrados.",
    actions: [
      "Cambiar entre la pestana de pendientes y la de historial.",
      "Consultar folio, descripcion, cliente, tipo de equipo, fecha de ingreso y estado actual.",
      "Trabajar desde tabla en escritorio o tarjetas responsivas en movil.",
      "Entrar al detalle del servicio para modificarlo o revisarlo.",
    ],
    workflow: [
      "Abre /servicios y elige la pestana adecuada segun lo que buscas.",
      "Ubica el folio por cliente, descripcion o estado visible en la tabla.",
      "Haz clic en Ver o sobre la tarjeta movil para abrir el detalle.",
      "Regresa al listado cuando termines de actualizar el servicio.",
    ],
    notes: [
      "Los estados se estilizan con colores para identificar prioridades rapidamente.",
      "El historial separa los servicios ya entregados del trabajo activo.",
      "La vista movil conserva la informacion principal y el acceso al detalle.",
      "Es la pantalla ideal para tecnicos y recepcionistas que monitorean la cola diaria.",
    ],
    figure: "servicesList",
  },
  {
    title: "Detalle del servicio y boleta",
    accent: "#e11d48",
    routeLabel: "Seguimiento tecnico: /servicios/:folio",
    tags: ["Estado", "QR y boleta"],
    summary:
      "El detalle del servicio es el centro operativo del expediente. Permite actualizar estado, fecha aproximada, observaciones, QR publico, notas internas y la boleta de venta con productos, pagos y cargos extra.",
    actions: [
      "Actualizar estatus como revision, espera de refaccion, listo, no reparable o entregado.",
      "Avisar al cliente por WhatsApp y compartir un QR para consulta publica del avance.",
      "Generar boleta con productos escaneados, forma de pago, notas y total acumulado.",
      "Guardar todo el expediente o generar el PDF de plantilla cuando la boleta ya esta lista.",
    ],
    workflow: [
      "Abre el folio y revisa el estado actual, costo y fecha prometida.",
      "Ajusta status, observaciones y cualquier foto o nota interna necesaria.",
      "Si habra cobro, captura o escanea articulos dentro de la boleta y valida el total.",
      "Guarda cambios y usa el PDF o el QR para compartir el seguimiento al cliente.",
    ],
    notes: [
      "La boleta puede incluir cargos de retardo segun la politica configurada.",
      "El QR dirige al cliente a la pagina publica de estatus del servicio.",
      "Las notas internas se manejan en un panel aparte para no mostrarlas al cliente.",
      "Este modulo concentra el historico real del trabajo tecnico.",
    ],
    figure: "serviceDetail",
  },
  {
    title: "Clientes y fidelizacion",
    accent: "#0891b2",
    routeLabel: "Relacion con clientes: /clientes y /clientes/:id",
    tags: ["Historial", "Puntos"],
    summary:
      "Clientes permite buscar contactos, revisar actividad, notas internas y servicios asociados. Si el programa de fidelidad esta activo, tambien muestra puntos, metas y opciones de canje.",
    actions: [
      "Buscar clientes por nombre o telefono desde una vista rapida.",
      "Abrir el perfil para ver servicios pendientes, historial, gasto total y ultima visita.",
      "Contactar por WhatsApp o correo con enlaces directos desde la ficha del cliente.",
      "Editar notas internas y saltar directo al detalle de cualquier servicio asociado.",
    ],
    workflow: [
      "Entra al listado y usa el buscador para localizar al cliente.",
      "Abre su ficha para revisar actividad, historial y nivel de relacion.",
      "Si aplica, consulta puntos acumulados, metas y productos canjeables.",
      "Desde la ficha abre el servicio correspondiente o actualiza notas internas.",
    ],
    notes: [
      "El programa visual de canjes se puede ocultar desde configuracion de servicios.",
      "La ficha del cliente muestra actividad por mes y ultimo servicio realizado.",
      "Es util para recepcion, seguimiento comercial y recompensas.",
      "Ayuda a evitar registros duplicados al reutilizar clientes existentes.",
    ],
    figure: "clients",
  },
  {
    title: "Punto de venta y ticket",
    accent: "#2563eb",
    routeLabel: "Cobro y caja: /POS",
    tags: ["Cobro", "Ticket"],
    summary:
      "POS integra venta de productos y cobro de servicios. Permite cargar productos, servicios listos, aplicar IVA, descuentos y registrar pagos antes de imprimir el ticket o la factura segun configuracion.",
    actions: [
      "Buscar productos por codigo o texto y agregarlos al carrito.",
      "Cargar servicios listos para cobro y relacionarlos con el cliente.",
      "Cobrar con efectivo, tarjeta o transferencia y registrar referencia de pago.",
      "Imprimir el ticket automaticamente, sumar puntos y descontar inventario.",
    ],
    workflow: [
      "Verifica que la caja este abierta y con fondo inicial registrado.",
      "Agrega productos o servicios al carrito desde buscador, escaner o selector.",
      "Abre el modal de pago, define montos y confirma la venta.",
      "Entrega el ticket y deja la venta disponible para reportes e historial.",
    ],
    notes: [
      "El POS puede usar vista movil para escanear desde telefono o tablet.",
      "La configuracion del ticket y la facturacion se define en Configuracion POS.",
      "El sistema puede imprimir tickets en silencioso si el puente local esta instalado.",
      "El servicio cobrado se refleja luego en reportes y corte de caja.",
    ],
    figure: "pos",
  },
  {
    title: "Inventario integrado",
    accent: "#16a34a",
    routeLabel: "Catalogo de inventario: /productos o /configuracion/inventario",
    tags: ["Stock", "Categorias"],
    summary:
      "Inventario comparte catalogo con POS y boletas del taller. Permite administrar productos, refacciones, servicios, accesorios y consumibles con stock, precios, datos fiscales y categorias.",
    actions: [
      "Crear o editar productos con un asistente dividido en identificacion, stock y facturacion.",
      "Gestionar categorias de inventario y explorar productos por categoria.",
      "Buscar por codigo de barras o clave interna para edicion rapida.",
      "Controlar margen, stock minimo, punto de reorden y estado del articulo.",
    ],
    workflow: [
      "Crea o revisa categorias antes de cargar nuevos productos.",
      "Captura datos base, precios, existencia y notas internas del articulo.",
      "Guarda el producto para que aparezca de inmediato en POS y boletas.",
      "Actualiza inventario cuando cambien precios, stock o datos fiscales.",
    ],
    notes: [
      "El mismo inventario alimenta ventas mostrador, boletas y configuracion de canjes.",
      "Los tipos incluyen producto, refaccion, servicio, accesorio y consumible.",
      "El modulo permite ubicar articulos por categoria, marca o proveedor.",
      "Es recomendable mantener claves y categorias consistentes para reportes limpios.",
    ],
    figure: "inventory",
  },
  {
    title: "Reportes, tickets y corte de caja",
    accent: "#7c3aed",
    routeLabel: "Analitica y cierre: /reportes",
    tags: ["Graficas", "Corte"],
    summary:
      "Reportes concentra ventas, servicios realizados, detalle de ventas, historial de cortes y cierres del dia. Tambien incluye egresos, graficas y herramientas para visualizar o reimprimir tickets.",
    actions: [
      "Filtrar ventas por fecha, texto o cajero para analizar resultados del periodo.",
      "Revisar graficas de ventas, unidades, utilidad y metodos de pago.",
      "Abrir historial de cortes, servicios realizados o detalle de ventas desde el navbar inferior.",
      "Visualizar o reimprimir tickets directamente desde las tablas operativas.",
    ],
    workflow: [
      "Define el rango de fechas y revisa los KPIs del bloque superior.",
      "Analiza graficas y usa la lista inferior para desglosar productos o servicios.",
      "Abre la pestana requerida: historial, servicios realizados o detalle de ventas.",
      "Al final del dia captura arqueo, egresos y confirma el cierre con PDF.",
    ],
    notes: [
      "El cierre de caja genera PDF y bloquea nuevos egresos del dia una vez confirmado.",
      "Los egresos se registran desde un modal dedicado y se reflejan en el corte.",
      "Las graficas pueden agrupar servicios y mostrar su desglose por separado.",
      "El historial ya muestra el nombre del cajero en lugar del correo.",
    ],
    figure: "reportes",
  },
  {
    title: "Configuracion general del sistema",
    accent: "#d97706",
    routeLabel: "Panel base: /configuracion",
    tags: ["Admin", "Panel central"],
    summary:
      "Configuracion funciona como centro administrativo. Desde un panel de tarjetas se accede a empresa, proveedores, empleados, POS, inventario, servicios, metodos de pago, apariencia, notificaciones e impresoras.",
    actions: [
      "Buscar rapidamente una configuracion usando el cuadro del Panel General.",
      "Revisar estadisticas globales, empleados activos y version del sistema.",
      "Abrir soporte por WhatsApp o correo desde la barra lateral derecha.",
      "Regresar al panel principal desde cualquier submodulo sin perder contexto.",
    ],
    workflow: [
      "Entra a /configuracion y ubica la tarjeta del modulo que deseas ajustar.",
      "Haz cambios en la subpantalla correspondiente y guarda la configuracion.",
      "Vuelve al Panel General para continuar con el siguiente bloque.",
      "Valida al final que los cambios se reflejen en operacion diaria.",
    ],
    notes: [
      "La vista lateral derecha muestra ventas, servicios y clientes acumulados.",
      "El panel tambien enseña presencia de empleados activos en tiempo real.",
      "Solo usuarios con permisos suficientes pueden entrar a estas pantallas.",
      "Es el punto ideal para preparar el sistema antes de iniciar operacion.",
    ],
    figure: "configPanel",
  },
  {
    title: "Empresa, servicios, POS e impresoras",
    accent: "#0f766e",
    routeLabel: "Config operativa: /configuracion/empresa, /servicios, /pos e /impresoras",
    tags: ["Personalizacion", "Impresion"],
    summary:
      "Las configuraciones operativas definen como se comporta el negocio: tipos de negocio y campos de hoja, precio de revision, terminos, politica de retardo, IVA, facturacion, ticket, impresoras separadas y autoimpresion.",
    actions: [
      "Editar nombre comercial, subtitulo y tipos de negocio con campos personalizados.",
      "Configurar hoja de servicio en PDF, terminos editables y cargos por retardo o abandono.",
      "Ajustar IVA, folios de facturacion y apariencia del ticket de venta.",
      "Elegir modo de impresion, impresora de tickets, impresora de hoja de servicio y tamano A4 o Carta.",
    ],
    workflow: [
      "Comienza por Empresa para dejar listo el tipo de negocio y los campos visibles.",
      "Continua en Servicios para precio de revision, canjes y reglas del expediente.",
      "Ajusta POS para IVA, ticket y facturacion segun la operacion del negocio.",
      "Termina en Impresoras con pruebas de impresion y el driver local si usaras modo silencioso.",
    ],
    notes: [
      "La hoja de servicio y los tickets pueden usar impresoras distintas.",
      "La impresion silenciosa requiere instalar el puente local en la PC del negocio.",
      "El documento al iniciar servicio puede ser ticket, hoja de servicio o ambos.",
      "Carta y A4 ya pueden definirse para la hoja de servicio desde configuracion.",
    ],
    figure: "configOps",
  },
  {
    title: "Empleados, proveedores y apariencia",
    accent: "#e11d48",
    routeLabel: "Config complementaria: /configuracion/empleados, /proveedores, /metodos, /apariencia y /notificaciones",
    tags: ["Equipo", "Control interno"],
    summary:
      "Estos modulos completan la administracion interna del sistema: alta de empleados, roles y permisos, directorio de proveedores, metodos de pago disponibles, tema visual y alertas del negocio.",
    actions: [
      "Registrar o editar empleados con nombre, telefono, correo, rol y estado.",
      "Asignar permisos finos y proteger el cargo de Super Administrador.",
      "Gestionar proveedores con secciones de datos, contacto, compras, pago y garantias.",
      "Definir metodos de pago, apariencia del sistema y preferencias de notificaciones.",
    ],
    workflow: [
      "Crea primero el equipo humano y sus permisos para delimitar accesos.",
      "Carga proveedores y datos de compra para ordenar mejor la operacion.",
      "Ajusta apariencia y notificaciones para el estilo de trabajo del negocio.",
      "Vuelve a probar el sistema con un usuario normal para validar permisos.",
    ],
    notes: [
      "Los permisos impactan directamente la barra superior y las rutas visibles.",
      "El modulo de empleados sincroniza datos con la coleccion de autorizados.",
      "Proveedores mantiene historico de compras y datos comerciales.",
      "Apariencia y notificaciones ayudan a adaptar la experiencia al equipo.",
    ],
    figure: "teamOps",
  },
  {
    title: "Consulta publica de estatus",
    accent: "#0891b2",
    routeLabel: "Consulta del cliente: /status, /status/scan y /status/:folio",
    tags: ["Cliente final", "QR"],
    summary:
      "La parte publica del sistema esta pensada para que el cliente consulte su avance sin entrar al panel interno. Puede capturar el folio manualmente o escanear el QR generado en el detalle del servicio o el ticket.",
    actions: [
      "Buscar un servicio por folio desde una pantalla publica simple.",
      "Abrir la camara del dispositivo para escanear el QR del ticket.",
      "Mostrar un stepper con estados como pendiente, revision, espera y reparacion.",
      "Compartir precio, fecha aproximada y observaciones segun el avance real del folio.",
    ],
    workflow: [
      "Entrega al cliente su ticket con QR o al menos el folio visible.",
      "El cliente entra a /status o /status/scan desde su telefono.",
      "Despues de capturar el folio, ve la linea de tiempo con su avance.",
      "Cada vez que el tecnico actualiza el servicio, la vista publica tambien cambia.",
    ],
    notes: [
      "Solo se muestran datos utiles para el cliente final, no notas internas.",
      "La experiencia esta optimizada para movil y camara trasera.",
      "Reduce llamadas de seguimiento y mejora la percepcion de orden del negocio.",
      "Es especialmente util para talleres y servicios tecnicos con varios pasos.",
    ],
    figure: "publicStatus",
  },
  {
    title: "Flujo diario recomendado y soporte",
    accent: "#2563eb",
    routeLabel: "Operacion sugerida: recepcion, seguimiento, cobro y cierre",
    tags: ["Checklist", "Soporte"],
    summary:
      "Para aprovechar el sistema conviene usar un flujo operativo estable: apertura, recepcion, seguimiento tecnico, cobro, reportes y cierre. Esta pagina resume la rutina sugerida y los puntos de soporte mas importantes.",
    actions: [
      "Abrir caja al iniciar turno y validar impresoras configuradas.",
      "Registrar servicios nuevos, actualizar estatus y documentar boletas durante el dia.",
      "Cobrar en POS, entregar ticket y compartir QR o folio al cliente.",
      "Registrar egresos, cerrar caja y descargar el PDF del corte al terminar la jornada.",
    ],
    workflow: [
      "Inicio del dia: revisar Inicio, caja, impresoras y notificaciones.",
      "Durante el dia: usar Hoja de servicio, Servicios, Clientes, Inventario y POS.",
      "Fin del dia: entrar a Reportes, confirmar egresos y cerrar caja con PDF.",
      "Mantenimiento: entrar a Configuracion cuando cambien empleados, impresoras o reglas del negocio.",
    ],
    notes: [
      "Si activas impresion silenciosa, instala el archivo Instalar_Puente_Impresora.cmd en cada PC.",
      "Conserva consistencia en categorias, tipos de servicio y metodos de pago para tener reportes limpios.",
      "Si un usuario no ve una pantalla, primero revisa sus permisos en Empleados.",
      "Soporte directo disponible en Configuracion mediante WhatsApp y correo del administrador del sistema.",
    ],
    figure: "workflow",
  },
];
